"""Add run execution metadata

Revision ID: 49aa85f512c9
Revises: 5c917a58d9e7
Create Date: 2026-09-23 16:44:28.619761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49aa85f512c9'
down_revision: Union[str, Sequence[str], None] = '5c917a58d9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('correlation_id', sa.String(length=36), nullable=True))
    op.execute(
        "UPDATE runs SET correlation_id = md5(random()::text || clock_timestamp()::text) "
        "WHERE correlation_id IS NULL"
    )
    op.alter_column('runs', 'correlation_id', nullable=False)
    op.add_column('runs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('runs', sa.Column('max_retries', sa.Integer(), server_default='2', nullable=False))
    op.add_column('runs', sa.Column('timeout_seconds', sa.Integer(), server_default='300', nullable=False))
    op.add_column('runs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_runs_correlation_id'), 'runs', ['correlation_id'], unique=True)
    op.create_check_constraint('ck_runs_max_retries', 'runs', 'max_retries >= 0')
    op.create_check_constraint('ck_runs_retry_count', 'runs', 'retry_count >= 0')
    op.create_check_constraint('ck_runs_timeout_seconds', 'runs', 'timeout_seconds > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_runs_timeout_seconds', 'runs', type_='check')
    op.drop_constraint('ck_runs_retry_count', 'runs', type_='check')
    op.drop_constraint('ck_runs_max_retries', 'runs', type_='check')
    op.drop_index(op.f('ix_runs_correlation_id'), table_name='runs')
    op.drop_column('runs', 'celery_task_id')
    op.drop_column('runs', 'timeout_seconds')
    op.drop_column('runs', 'max_retries')
    op.drop_column('runs', 'retry_count')
    op.drop_column('runs', 'correlation_id')
    # ### end Alembic commands ###
