"""Add domain status constraints and indexes

Revision ID: 5c917a58d9e7
Revises: 25570d9664e4
Create Date: 2026-09-23 16:29:41.908713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c917a58d9e7'
down_revision: Union[str, Sequence[str], None] = '25570d9664e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Preserve existing data while standardizing the validation lifecycle name.
    op.execute("UPDATE validations SET status = 'success' WHERE status = 'passed'")
    op.create_index(op.f('ix_deployments_run_id'), 'deployments', ['run_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_check_constraint('ck_deployments_status', 'deployments', "status IN ('pending', 'running', 'success', 'failed', 'cancelled')")
    op.create_check_constraint('ck_deployments_timestamps', 'deployments', 'finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at')
    op.create_index(op.f('ix_generated_files_path'), 'generated_files', ['path'], unique=False)
    op.create_index(op.f('ix_generated_files_run_id'), 'generated_files', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipelines_project_id'), 'pipelines', ['project_id'], unique=False)
    op.create_index(op.f('ix_pipelines_status'), 'pipelines', ['status'], unique=False)
    op.create_check_constraint('ck_pipelines_status', 'pipelines', "status IN ('active', 'inactive')")
    op.create_index(op.f('ix_runs_pipeline_id'), 'runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_check_constraint('ck_runs_status', 'runs', "status IN ('pending', 'running', 'success', 'failed', 'cancelled')")
    op.create_check_constraint('ck_runs_timestamps', 'runs', 'finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at')
    op.drop_constraint(op.f('token_blacklist_jti_key'), 'token_blacklist', type_='unique')
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_foreign_key(
        'fk_token_blacklist_user_id_users',
        'token_blacklist',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_index(op.f('ix_validations_run_id'), 'validations', ['run_id'], unique=False)
    op.create_index(op.f('ix_validations_status'), 'validations', ['status'], unique=False)
    op.create_check_constraint('ck_validations_status', 'validations', "status IN ('pending', 'running', 'success', 'failed', 'cancelled')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_validations_status', 'validations', type_='check')
    op.drop_index(op.f('ix_validations_status'), table_name='validations')
    op.drop_index(op.f('ix_validations_run_id'), table_name='validations')
    op.drop_constraint(
        'fk_token_blacklist_user_id_users', 'token_blacklist', type_='foreignkey'
    )
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.create_unique_constraint(op.f('token_blacklist_jti_key'), 'token_blacklist', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('ck_runs_timestamps', 'runs', type_='check')
    op.drop_constraint('ck_runs_status', 'runs', type_='check')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_pipeline_id'), table_name='runs')
    op.drop_constraint('ck_pipelines_status', 'pipelines', type_='check')
    op.drop_index(op.f('ix_pipelines_status'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_project_id'), table_name='pipelines')
    op.drop_index(op.f('ix_generated_files_run_id'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_path'), table_name='generated_files')
    op.drop_constraint('ck_deployments_timestamps', 'deployments', type_='check')
    op.drop_constraint('ck_deployments_status', 'deployments', type_='check')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_run_id'), table_name='deployments')
    # ### end Alembic commands ###
